import React from 'react';

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5bXR2Lw54l9
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { Icons } from '@/components/icons';

const DUMMY_DATA = {
  date: ['28', '29', '30', '1', '2', '3', '4'],
};

const DAY_OF_WEEK = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const HOURS_OF_DAY = [
  '12 AM',
  '1 AM',
  '2 AM',
  '3 AM',
  '4 AM',
  '5 AM',
  '6 AM',
  '7 AM',
  '8 AM',
  '9 AM',
  '10 AM',
  '11 AM',
  '12 PM',
  '1 PM',
  '2 PM',
  '3 PM',
  '4 PM',
  '5 PM',
  '6 PM',
  '7 PM',
  '8 PM',
  '9 PM',
  '10 PM',
  '11 PM',
];

export default function BookingCalendar() {
  return (
    <div className="w-full">
      <div className="flex w-full items-center justify-between py-2">
        <h3 className="text-2xl font-semibold md:text-3xl">2024 April</h3>
        <div className="flex">
          <Button variant="ghost" size="icon">
            <Icons.ChevronLeft className="h-4 w-4" />
          </Button>
          <Button variant="ghost">Today</Button>
          <Button variant="ghost" size="icon">
            <Icons.ChevronRight className="h-4 w-4" />
          </Button>
        </div>
      </div>
      <Table className="w-full table-fixed">
        <TableHeader>
          <TableRow>
            <TableHead className="w-10 md:w-14" />
            {DAY_OF_WEEK.map((day, index) => (
              <TableHead key={day} className="p-0 text-xs">
                <div className="flex flex-col items-center justify-center md:flex-row md:gap-x-2 md:text-base">
                  <p>{DUMMY_DATA.date[index]}</p>
                  <p>{day}</p>
                </div>
              </TableHead>
            ))}
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow>
            <TableCell colSpan={8} className="p-0">
              <Button
                variant="ghost"
                className="flex h-8 w-full items-center justify-center"
              >
                <Icons.ChevronsUp className="h-4" />
              </Button>
            </TableCell>
          </TableRow>
          {HOURS_OF_DAY.map((hour) => (
            <TableRow key={hour}>
              <TableCell className="p-0 text-xs text-muted-foreground">
                {hour}
              </TableCell>
              {DAY_OF_WEEK.map((day) => (
                <TableCell key={day} className="px-1 sm:px-2">
                  <Button variant="outline" className="h-8 w-full">
                    <Icons.Plus className="w-4 min-w-2" />
                  </Button>
                </TableCell>
              ))}
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}
